################################################################################
# Specify the Default settings to be used.
#
agentPool: dev
resources:
  limits:
    cpu: 2
    memory: 8
  requests:
    cpu: 0.2
elasticsearch:
  nodeCount: 3
  storagePerNodeGB: 128

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer-staging
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  tls:
  - secretName: https-certificate
    hosts:
    - elastic-instance.eastus2.cloudapp.azure.com
  hosts:
  - host: elastic-instance.eastus2.cloudapp.azure.com
    path: "/(.*)"
    service: elasticsearch-es-http
    port: 9200