name: '6. Stamp Uninstall'

on:
  workflow_dispatch:

env:
  CLI_VERSION: 2.30.0

jobs:

  delete:
    name: Uninstall Process
    runs-on: ubuntu-latest

    steps:
      - uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      -  uses: actions/checkout@v2
      - name: Install Flux
        run: curl -s https://fluxcd.io/install.sh | bash;

      - name: Environment Settings
        uses: Azure/cli@1.0.4
        with:
          azcliversion: ${{ env.CLI_VERSION }}
          inlineScript: |
            GROUP=$(az group list --query "[?contains(name, 'dpl${{ secrets.RAND }}')].name" -otsv |grep -v MC)
            ENV_CLUSTER=$(az aks list --resource-group $GROUP --query [].name -otsv)
            echo "CLUSTER_RESOURCE_GROUP=$GROUP" >> $GITHUB_ENV
            echo "CLUSTER_NAME=$ENV_CLUSTER" >> $GITHUB_ENV
      - name: AKS Context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      - name: Suspend Kustomization
        env:
          OK: ${{ secrets.UNINSTALL }}
        if: contains(env.OK, 'true')
        run: |
          flux suspend kustomization flux-system
          flux suspend kustomization osdu-stamp

      - name: Uninstall osdu-azure
        env:
          OK: ${{ secrets.UNINSTALL }}
          NAMESPACE: osdu-azure
        if: contains(env.OK, 'true')
        run: |
          CHARTS=('ddms-wellbore' \
                  'ddms-seismic' \
                  'workflow-service' \
                  'wks-service' \
                  'crs-catalog' \
                  'crs-conversion' \
                  'unit-service' \
                  'register-service' \
                  'notification-service' \
                  'search-service' \
                  'indexer-queue' \
                  'indexer-service' \
                  'storage-service' \
                  'dataset-service' \
                  'file-service' \
                  'schema-service' \
                  'legal-service' \
                  'entitlement-service' \
                  'partition-service' \
                  'default-service' \
                  'self-managed-base'
                  )
          for CHART in "${CHARTS[@]}"
          do
            if [ ! -z $(helm status $CHART -n $NAMESPACE -o json |jq -r ".info.status") ]
            then
              flux delete helmrelease $CHART -n $NAMESPACE --silent
            fi
          done

      - name: Uninstall dev-sample
        env:
          OK: ${{ secrets.UNINSTALL }}
          NAMESPACE: dev-sample
        if: contains(env.OK, 'true')
        run: |
          if [ ! -z $(helm status dev-sample-env-tool -n dev-sample -o json |jq -r ".info.status") ]
          then
            flux delete helmrelease dev-sample-env-tool -n dev-sample --silent
          fi
          if [ ! -z $(helm status token-service -n dev-sample -o json |jq -r ".info.status") ]
          then
            flux delete helmrelease token-service -n dev-sample --silent
          fi

      - name: Uninstall osdu-airflow
        env:
          OK: ${{ secrets.UNINSTALL }}
          NAMESPACE: airflow
        if: contains(env.OK, 'true')
        run: |
          if [ ! -z $(helm status airflow -n $NAMESPACE -o json |jq -r ".info.status") ]
          then
            helm uninstall airflow -n $NAMESPACE
          fi
          if [ ! -z $(helm status airflow-base -n $NAMESPACE -o json |jq -r ".info.status") ]
          then
            flux delete helmrelease airflow-base -n $NAMESPACE --silent
          fi

      - name: Uninstall Elastic
        env:
          OK: ${{ secrets.UNINSTALL }}
          NAMESPACE: elastic-system
        if: contains(env.OK, 'true')
        run: |
          if [ ! -z $(helm status eck -n $NAMESPACE -o json |jq -r ".info.status") ]
          then
            helm uninstall eck -n $NAMESPACE
          fi



      - name: Uninstall osdu-istio
        env:
          OK: ${{ secrets.UNINSTALL }}
          NAMESPACE: istio-system
        if: contains(env.OK, 'true')
        run: |
          CHARTS=('osdu-istio' 'istio-operator' 'istio-base')
          for CHART in "${CHARTS[@]}"
          do
            if [ ! -z $(helm status $CHART -n $NAMESPACE -o json |jq -r ".info.status") ]
            then
              flux delete helmrelease $CHART -n $NAMESPACE --silent
            fi
          done

      - name: Uninstall osdu-base
        env:
          OK: ${{ secrets.UNINSTALL }}
        if: contains(env.OK, 'true')
        run: |
          if [ ! -z $(helm status osdu-base -n default -o json |jq -r ".info.status") ]
          then
            flux delete helmrelease osdu-base -n default --silent
          fi

      - name: Uninstall Kustomizations
        env:
          OK: ${{ secrets.UNINSTALL }}
        if: contains(env.OK, 'true')
        run: |
          if [ ! -z $(kubectl get sealed-secrets -n flux-system --ignore-not-found) ]
          then
            flux delete kustomization sealed-secrets --silent
          fi
          if [ ! -z $(kubectl get kustomization osdu-stamp -n osdu-azure --ignore-not-found) ]
          then
            flux delete kustomization osdu-stamp --silent
          fi

      - name: Remove Namespaces
        env:
          OK: ${{ secrets.UNINSTALL }}
        if: contains(env.OK, 'true')
        run: |
          kubectl delete CustomResourceDefinition istiooperators.install.istio.io --ignore-not-found
          kubectl delete namespace ddms-wellbore --ignore-not-found
          kubectl delete namespace ddms-seismic --ignore-not-found
          kubectl delete namespace osdu-azure --ignore-not-found
          kubectl delete namespace dev-sample --ignore-not-found
          kubectl delete namespace airflow --ignore-not-found
          kubectl delete namespace elastic-instance --ignore-not-found
          kubectl delete namespace elastic-system --ignore-not-found
          kubectl delete namespace istio-system --ignore-not-found

      - name: Remove osdu-stamp
        env:
          OK: ${{ secrets.UNINSTALL }}
        if: contains(env.OK, 'true')
        run: |
          rm -rf clusters/osdu-stamp
          rm -rf apps/osdu-stamp

      - name: Git CheckIn
        env:
          OK: ${{ secrets.UNINSTALL }}
        if: contains(env.OK, 'true')
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Software Removed'
          add: '.'

      - name: Remove Flux
        env:
          OK: ${{ secrets.UNINSTALL }}
        if: contains(env.OK, 'true')
        run: |
          flux uninstall --silent

      - name: Delete Infrastructure
        uses: Azure/cli@1.0.4
        env:
          OK: ${{ secrets.REMOVE }}
        if: contains(env.OK, 'true')
        with:
          azcliversion: ${{ env.CLI_VERSION }}
          inlineScript: |
            DASHBOARD=$(az group list --query "[?contains(name, 'dash${{ secrets.RAND }}')].name" -otsv |grep -v MC)
            PARTITION=$(az group list --query "[?contains(name, 'prt${{ secrets.RAND }}')].name" -otsv |grep -v MC)
            DATA_PLANE=$(az group list --query "[?contains(name, 'dpl${{ secrets.RAND }}')].name" -otsv |grep -v MC)
            CONTROL_PLANE=$(az group list --query "[?contains(name, 'cpl${{ secrets.RAND }}')].name" -otsv |grep -v MC)
            BUILDER_GROUP=osdu-builder-${{ secrets.RAND }}
            az group delete -n $DASHBOARD --yes --no-wait
            az group delete -n $PARTITION --yes --no-wait
            az group delete -n $DATA_PLANE --yes --no-wait
            az group delete -n $CONTROL_PLANE --yes --no-wait
            az group delete -n $BUILDER_GROUP --yes --no-wait

      - name: Remove osdu-stamp
        env:
          OK: ${{ secrets.REMOVE }}
        if: contains(env.OK, 'true')
        run: |
          rm -rf clusters/osdu-stamp
          rm -rf apps/osdu-stamp

      - name: Git CheckIn
        env:
          OK: ${{ secrets.REMOVE }}
        if: contains(env.OK, 'true')
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Software Removed'
          add: '.'
